Repository hassio-addons/addon-tor, pull requests merged in 2022-06, with the labels that each got.

#136 ⬆️ Upgrades add-on base image to 12.0.0
  tor/Dockerfile
  tor/build.yaml
  tor/config.yaml
  tor/rootfs/etc/cont-init.d/10-requirements.sh
  tor/rootfs/etc/cont-init.d/20-dirs.sh
  tor/rootfs/etc/cont-init.d/50-tor-log.sh
  tor/rootfs/etc/cont-init.d/51-tor-socks.sh
  tor/rootfs/etc/cont-init.d/52-tor-services.sh
  tor/rootfs/etc/cont-init.d/90-hostname.sh
  tor/rootfs/etc/services.d/tor/finish
  tor/rootfs/etc/services.d/tor/run
Labels: minor, dependencies

#137 :ambulance: Fix deployment of add-on
  .github/workflows/deploy.yaml
Labels: ci

#138 :fireworks: Updates maintenance/license year to 2022
  LICENSE.md
  README.md
  tor/.README.j2
  tor/DOCS.md
Labels: maintenance

#139 :fire: Clean up obsolete fixattrs.d
  tor/rootfs/etc/fix-attrs.d/10-tor
Labels: maintenance

#105 🚑 Fix Hidden Service V3 Client Authorization
  tor/Dockerfile
  tor/rootfs/etc/cont-init.d/20-dirs.sh
  tor/rootfs/etc/cont-init.d/52-tor-services.sh
  tor/rootfs/etc/cont-init.d/90-hostname.sh
Labels: bugfix

#140 📚 Add My button to documentation
  tor/DOCS.md
Labels: documentation

#141 :shirt: Change ports default to use port 80
  tor/config.yaml
Labels: enhancement

#142 :earth_americas: Add translations files
  tor/translations/en.yaml
Labels: enhancement

#143 :hammer: Refactor container init
  tor/rootfs/etc/cont-init.d/10-requirements.sh
  tor/rootfs/etc/cont-init.d/20-dirs.sh
  tor/rootfs/etc/cont-init.d/50-tor-log.sh
  tor/rootfs/etc/cont-init.d/51-tor-socks.sh
  tor/rootfs/etc/cont-init.d/52-tor-services.sh
  tor/rootfs/etc/cont-init.d/90-hostname.sh
  tor/rootfs/etc/cont-init.d/prepare.sh
Labels: enhancement
